/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareRouteImport } from './routes/share'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DigestIdRouteImport } from './routes/digest.$id'
import { Route as ApiCronExamBriefsRouteImport } from './routes/api/cron/exam-briefs'

const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestIdRoute = DigestIdRouteImport.update({
  id: '/digest/$id',
  path: '/digest/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronExamBriefsRoute = ApiCronExamBriefsRouteImport.update({
  id: '/api/cron/exam-briefs',
  path: '/api/cron/exam-briefs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exam': typeof ExamRoute
  '/login': typeof LoginRoute
  '/share': typeof ShareRoute
  '/digest/$id': typeof DigestIdRoute
  '/api/cron/exam-briefs': typeof ApiCronExamBriefsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exam': typeof ExamRoute
  '/login': typeof LoginRoute
  '/share': typeof ShareRoute
  '/digest/$id': typeof DigestIdRoute
  '/api/cron/exam-briefs': typeof ApiCronExamBriefsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exam': typeof ExamRoute
  '/login': typeof LoginRoute
  '/share': typeof ShareRoute
  '/digest/$id': typeof DigestIdRoute
  '/api/cron/exam-briefs': typeof ApiCronExamBriefsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exam'
    | '/login'
    | '/share'
    | '/digest/$id'
    | '/api/cron/exam-briefs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exam'
    | '/login'
    | '/share'
    | '/digest/$id'
    | '/api/cron/exam-briefs'
  id:
    | '__root__'
    | '/'
    | '/exam'
    | '/login'
    | '/share'
    | '/digest/$id'
    | '/api/cron/exam-briefs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamRoute: typeof ExamRoute
  LoginRoute: typeof LoginRoute
  ShareRoute: typeof ShareRoute
  DigestIdRoute: typeof DigestIdRoute
  ApiCronExamBriefsRoute: typeof ApiCronExamBriefsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digest/$id': {
      id: '/digest/$id'
      path: '/digest/$id'
      fullPath: '/digest/$id'
      preLoaderRoute: typeof DigestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/exam-briefs': {
      id: '/api/cron/exam-briefs'
      path: '/api/cron/exam-briefs'
      fullPath: '/api/cron/exam-briefs'
      preLoaderRoute: typeof ApiCronExamBriefsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamRoute: ExamRoute,
  LoginRoute: LoginRoute,
  ShareRoute: ShareRoute,
  DigestIdRoute: DigestIdRoute,
  ApiCronExamBriefsRoute: ApiCronExamBriefsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
