/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareRouteImport } from './routes/share'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamIndexRouteImport } from './routes/exam.index'
import { Route as ExamArchiveRouteImport } from './routes/exam.archive'
import { Route as DigestIdRouteImport } from './routes/digest.$id'
import { Route as ExamArchiveIndexRouteImport } from './routes/exam.archive.index'
import { Route as ExamArchiveDateRouteImport } from './routes/exam.archive.$date'
import { Route as ApiCronExamBriefsRouteImport } from './routes/api/cron/exam-briefs'

const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamIndexRoute = ExamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamRoute,
} as any)
const ExamArchiveRoute = ExamArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => ExamRoute,
} as any)
const DigestIdRoute = DigestIdRouteImport.update({
  id: '/digest/$id',
  path: '/digest/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamArchiveIndexRoute = ExamArchiveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamArchiveRoute,
} as any)
const ExamArchiveDateRoute = ExamArchiveDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => ExamArchiveRoute,
} as any)
const ApiCronExamBriefsRoute = ApiCronExamBriefsRouteImport.update({
  id: '/api/cron/exam-briefs',
  path: '/api/cron/exam-briefs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exam': typeof ExamRouteWithChildren
  '/login': typeof LoginRoute
  '/share': typeof ShareRoute
  '/digest/$id': typeof DigestIdRoute
  '/exam/archive': typeof ExamArchiveRouteWithChildren
  '/exam/': typeof ExamIndexRoute
  '/api/cron/exam-briefs': typeof ApiCronExamBriefsRoute
  '/exam/archive/$date': typeof ExamArchiveDateRoute
  '/exam/archive/': typeof ExamArchiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/share': typeof ShareRoute
  '/digest/$id': typeof DigestIdRoute
  '/exam': typeof ExamIndexRoute
  '/api/cron/exam-briefs': typeof ApiCronExamBriefsRoute
  '/exam/archive/$date': typeof ExamArchiveDateRoute
  '/exam/archive': typeof ExamArchiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exam': typeof ExamRouteWithChildren
  '/login': typeof LoginRoute
  '/share': typeof ShareRoute
  '/digest/$id': typeof DigestIdRoute
  '/exam/archive': typeof ExamArchiveRouteWithChildren
  '/exam/': typeof ExamIndexRoute
  '/api/cron/exam-briefs': typeof ApiCronExamBriefsRoute
  '/exam/archive/$date': typeof ExamArchiveDateRoute
  '/exam/archive/': typeof ExamArchiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exam'
    | '/login'
    | '/share'
    | '/digest/$id'
    | '/exam/archive'
    | '/exam/'
    | '/api/cron/exam-briefs'
    | '/exam/archive/$date'
    | '/exam/archive/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/share'
    | '/digest/$id'
    | '/exam'
    | '/api/cron/exam-briefs'
    | '/exam/archive/$date'
    | '/exam/archive'
  id:
    | '__root__'
    | '/'
    | '/exam'
    | '/login'
    | '/share'
    | '/digest/$id'
    | '/exam/archive'
    | '/exam/'
    | '/api/cron/exam-briefs'
    | '/exam/archive/$date'
    | '/exam/archive/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamRoute: typeof ExamRouteWithChildren
  LoginRoute: typeof LoginRoute
  ShareRoute: typeof ShareRoute
  DigestIdRoute: typeof DigestIdRoute
  ApiCronExamBriefsRoute: typeof ApiCronExamBriefsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/': {
      id: '/exam/'
      path: '/'
      fullPath: '/exam/'
      preLoaderRoute: typeof ExamIndexRouteImport
      parentRoute: typeof ExamRoute
    }
    '/exam/archive': {
      id: '/exam/archive'
      path: '/archive'
      fullPath: '/exam/archive'
      preLoaderRoute: typeof ExamArchiveRouteImport
      parentRoute: typeof ExamRoute
    }
    '/digest/$id': {
      id: '/digest/$id'
      path: '/digest/$id'
      fullPath: '/digest/$id'
      preLoaderRoute: typeof DigestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/archive/': {
      id: '/exam/archive/'
      path: '/'
      fullPath: '/exam/archive/'
      preLoaderRoute: typeof ExamArchiveIndexRouteImport
      parentRoute: typeof ExamArchiveRoute
    }
    '/exam/archive/$date': {
      id: '/exam/archive/$date'
      path: '/$date'
      fullPath: '/exam/archive/$date'
      preLoaderRoute: typeof ExamArchiveDateRouteImport
      parentRoute: typeof ExamArchiveRoute
    }
    '/api/cron/exam-briefs': {
      id: '/api/cron/exam-briefs'
      path: '/api/cron/exam-briefs'
      fullPath: '/api/cron/exam-briefs'
      preLoaderRoute: typeof ApiCronExamBriefsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExamArchiveRouteChildren {
  ExamArchiveDateRoute: typeof ExamArchiveDateRoute
  ExamArchiveIndexRoute: typeof ExamArchiveIndexRoute
}

const ExamArchiveRouteChildren: ExamArchiveRouteChildren = {
  ExamArchiveDateRoute: ExamArchiveDateRoute,
  ExamArchiveIndexRoute: ExamArchiveIndexRoute,
}

const ExamArchiveRouteWithChildren = ExamArchiveRoute._addFileChildren(
  ExamArchiveRouteChildren,
)

interface ExamRouteChildren {
  ExamArchiveRoute: typeof ExamArchiveRouteWithChildren
  ExamIndexRoute: typeof ExamIndexRoute
}

const ExamRouteChildren: ExamRouteChildren = {
  ExamArchiveRoute: ExamArchiveRouteWithChildren,
  ExamIndexRoute: ExamIndexRoute,
}

const ExamRouteWithChildren = ExamRoute._addFileChildren(ExamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamRoute: ExamRouteWithChildren,
  LoginRoute: LoginRoute,
  ShareRoute: ShareRoute,
  DigestIdRoute: DigestIdRoute,
  ApiCronExamBriefsRoute: ApiCronExamBriefsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
